In [1]:
## Multi Layer Neural network

In [2]:
## in previous Notebook we have seen used single layer perceptron neural network and  Bi gram stats model both of them cannot capture the context better, they dont sound the names better
# so in this notebook we use the multilayer perceptron which are useful to generate the meaning full name

# so the problem with bi-gram model we face is we are able to capture the context of 2 characters at a time.(that gives us 27 character * 27 characters = 729 possibilities combination comes in context)
# if we have the 3 characters as context  we would get (27*27*27 =19,623 combinations context) generating count vector normalizing and everything becomes difficult now.
# the modeling approach we gonna follow  is from this research paper bengio et al. 2003 (https://www.jmlr.org/papers/volume3/bengio03a/bengio03a.pdf)


In [3]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
words = open('names.txt', 'r').read().splitlines()
words[:5]

['emma', 'olivia', 'ava', 'isabella', 'sophia']

In [5]:
chars = sorted(list(set(''.join(words))))
stoi = {
    s: i+1 for i,s in enumerate(chars)
}
stoi['.'] = 0
itos = { i:s for s,i in stoi.items() }


## Creating dataset for Neural Networks from Text File to Input Tensor and Output Tensor

In [6]:
## data set for neural network

block_size = 3 #Context_length: how many characters do we take to predict the next one?
X,Y =[],[] # X are the input to neural network and Y are  the labels of the neural network

for w in words[:1]:

    print(w)
    context = [0] * block_size

    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)

        print("input data : ",''.join(itos[i] for i in context), ", Output :", '=', itos[ix])
        print('context :', context)
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)


print('\n')
print("input tensor :", X)

print("output tensor :", Y)

emma
input data :  ... , Output : = e
context : [0, 0, 0]
input data :  ..e , Output : = m
context : [0, 0, 5]
input data :  .em , Output : = m
context : [0, 5, 13]
input data :  emm , Output : = a
context : [5, 13, 13]
input data :  mma , Output : = .
context : [13, 13, 1]


input tensor : tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1]])
output tensor : tensor([ 5, 13, 13,  1,  0])


In [7]:
"""
Above output explanation

you can notes how the input data is store in the input tensor it is simple

input data :  ... , Output : = e
context : [0, 0, 0]

when we get input '...' we have the o/p as 'e'
similary i/p = '..e' => o/p = 'm'

-> we are trying to take context of 3 character at same time and trying to predict the o/p of what character come next and run in the loop

1)so we are able to use above block and change the parameters like block size to get different context
2) if we consider all the input and one cblock size we are able to get the whole i/p and o/p data



"""

"\nAbove output explanation\n\nyou can notes how the input data is store in the input tensor it is simple\n\ninput data :  ... , Output : = e\ncontext : [0, 0, 0]\n\nwhen we get input '...' we have the o/p as 'e'\nsimilary i/p = '..e' => o/p = 'm'\n\n-> we are trying to take context of 3 character at same time and trying to predict the o/p of what character come next and run in the loop\n\n1)so we are able to use above block and change the parameters like block size to get different context\n2) if we consider all the input and one cblock size we are able to get the whole i/p and o/p data\n\n\n\n"

# Block size = 5

In [8]:
block_size = 5 #Context_length: how many characters do we take to predict the next one?
X,Y =[],[] # x are inputs and Y are labels

for w in words[:1]:

    print( 'word is :',w)

    print('\n')
    print('input -->  output')
    context = [0] * block_size

    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)

        print(''.join(itos[i] for i in context), "--> ", itos[ix])
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)


print('\n')
print("input tensor :", X)

print("output tensor :", Y)

word is : emma


input -->  output
..... -->  e
....e -->  m
...em -->  m
..emm -->  a
.emma -->  .


input tensor : tensor([[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  5],
        [ 0,  0,  0,  5, 13],
        [ 0,  0,  5, 13, 13],
        [ 0,  5, 13, 13,  1]])
output tensor : tensor([ 5, 13, 13,  1,  0])


In [9]:
X

tensor([[ 0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  5],
        [ 0,  0,  0,  5, 13],
        [ 0,  0,  5, 13, 13],
        [ 0,  5, 13, 13,  1]])

In [10]:
import pandas as pd
pd.DataFrame(Y)

0
0   5
1  13
2  13
3   1
4   0

### above we are trying to take 5 character as input and predicting what comes next as o/p

In [11]:
block_size = 3 #Context_length: how many characters do we take to predict the next one?
X,Y =[],[] # x are inputs and Y are labels

for w in words[:5]:

    #print(w)
    context = [0] * block_size

    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)

        #print("input data : ",''.join(itos[i] for i in context), ", Output :", '=', itos[ix])
        #print('context :', context)
        context = context[1:] + [ix]

X = torch.tensor(X)
Y = torch.tensor(Y)
X

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1],
        [ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  1, 22],
        [ 1, 22,  1],
        [ 0,  0,  0],
        [ 0,  0,  9],
        [ 0,  9, 19],
        [ 9, 19,  1],
        [19,  1,  2],
        [ 1,  2,  5],
        [ 2,  5, 12],
        [ 5, 12, 12],
        [12, 12,  1],
        [ 0,  0,  0],
        [ 0,  0, 19],
        [ 0, 19, 15],
        [19, 15, 16],
        [15, 16,  8],
        [16,  8,  9],
        [ 8,  9,  1]])

In [12]:
import pandas as pd
pd.DataFrame(Y)

0
0    5
1   13
2   13
3    1
4    0
5   15
6   12
7    9
8   22
9    9
10   1
11   0
12   1
13  22
14   1
15   0
16   9
17  19
18   1
19   2
20   5
21  12
22  12
23   1
24   0
25  19
26  15
27  16
28   8
29   9
30   1
31   0

In [13]:
"""
Training Data is ready
1. now the TRain data with the block_size/context = 3 is ready and o/p is also ready fo the model to get trained on.
"""

'\nTraining Data is ready\n1. now the TRain data with the block_size/context = 3 is ready and o/p is also ready fo the model to get trained on.\n'

In [14]:
(X.shape, X.dtype), (Y.shape, Y.dtype)

((torch.Size([32, 3]), torch.int64), (torch.Size([32]), torch.int64))

In [15]:
## so our tensor matrix x has 228146 rows and 3 columns only both of there dtype is integer

## In paper they have 17,000 words and they embedded in 30 dimensional

## in our case we have only 27 possible characters so let's consider 2- dimensional space so we have 27 charcter with 2 dimenisonal space(27*2) tensor

In [16]:
# let embedded the 2 random numbers with 27*2

C = torch.randn((27,2)) # this is used as an embedding layer
C

tensor([[-2.6265e-01, -5.7562e-01],
        [ 4.3103e-01, -1.4376e+00],
        [ 8.2138e-01, -2.7323e-01],
        [ 8.8447e-01,  1.4804e+00],
        [-4.5491e-01, -1.7313e-01],
        [-9.8686e-01,  5.4246e-04],
        [-1.0636e-01, -5.8234e-01],
        [ 4.4966e-01,  1.1518e+00],
        [ 6.4602e-01, -1.2099e+00],
        [-1.6913e-01, -1.6939e+00],
        [ 3.7878e-01,  1.8156e-01],
        [-1.1004e-01,  4.3457e-01],
        [-1.0578e+00,  1.5091e-01],
        [ 1.4987e+00,  1.0107e+00],
        [-1.5612e+00, -6.8247e-01],
        [ 3.7086e-03,  3.8279e-01],
        [-1.2025e+00,  6.8690e-02],
        [-6.4464e-01, -5.7007e-01],
        [ 6.7176e-02,  9.2242e-01],
        [ 2.1345e-01,  7.2505e-01],
        [ 5.1182e-01, -5.8370e-01],
        [ 9.5653e-01, -3.5498e-01],
        [ 1.0434e+00, -1.5332e+00],
        [-9.9752e-01, -5.3241e-01],
        [-2.6609e-02, -1.0094e+00],
        [-9.0189e-01, -2.2955e+00],
        [ 8.8348e-01,  2.1801e-01]])

In [17]:
C[5]

tensor([-9.8686e-01,  5.4246e-04])

In [18]:
#Example of encoding the number 5 with number of classes = 27(charac) and multiplying it with the weights matrix
# [1*27] @ [27*2] = [1*2] tensor

(F.one_hot(torch.tensor(5), num_classes=27).float()) @ C

tensor([-9.8686e-01,  5.4246e-04])

In [19]:
 # if we multiply the embedding vector(C) * index_vector/one_hot encoding vector of the input(X) = we get the Result from the first layer

In [20]:
C = torch.randn((27,2))
C ## c is noting buit one type of encoding

tensor([[-0.4801, -0.5718],
        [-0.3303,  0.4769],
        [-0.1991,  0.0677],
        [ 0.5129,  0.9135],
        [-0.4071, -1.4313],
        [ 0.4187,  1.1150],
        [ 0.8956, -0.4083],
        [ 0.3990, -0.2001],
        [-0.1843,  2.0090],
        [-0.3285,  0.0651],
        [-0.6277,  1.2797],
        [-0.1945,  2.2645],
        [ 0.5152, -0.1842],
        [ 1.0437, -0.2197],
        [-0.5586,  1.5264],
        [ 1.0341,  0.2543],
        [ 0.9467, -1.4448],
        [-0.5550,  0.5129],
        [-1.6583, -0.6111],
        [-2.5221, -0.1362],
        [ 1.3103, -0.2016],
        [ 0.8770, -0.6936],
        [ 1.3031,  1.1813],
        [ 0.3493,  2.4033],
        [ 1.6857, -0.6433],
        [-0.1681,  0.7351],
        [-1.3295, -0.2232]])

In [21]:
# we want to encode one number 5 we can simply pass this number to the Embedding tensor C and get the output i.e.,

C[5] #Give embedding of 5 in 2d Vector Space

tensor([0.4187, 1.1150])

In [22]:
# what if the embedding is like list

print(C[[2,3,4]]) # we got the embedding of 3 integer vector as below


tensor([[-0.1991,  0.0677],
        [ 0.5129,  0.9135],
        [-0.4071, -1.4313]])


In [23]:
# what if we give the tensor input to get embedding

print(C[torch.tensor([5,6,7,7,7,7,7,7,])]) # still we are able to get the embedding by giving tensor matrix as input

tensor([[ 0.4187,  1.1150],
        [ 0.8956, -0.4083],
        [ 0.3990, -0.2001],
        [ 0.3990, -0.2001],
        [ 0.3990, -0.2001],
        [ 0.3990, -0.2001],
        [ 0.3990, -0.2001],
        [ 0.3990, -0.2001]])


In [24]:
"""
Full explanation of C

 C is the embedding vector  when you pass the single integer -> we get the embedding of that single integer
if we pass list to embedding vector c -> we goonna get embedding for that list passed
if we pass the tensor to embedding vector -. we gonna get th emebedding for that tensor


to get emebedding for anything we need to pass it to the C

"""

'\nFull explanation of C\n\n C is the embedding vector  when you pass the single integer -> we get the embedding of that single integer\nif we pass list to embedding vector c -> we goonna get embedding for that list passed\nif we pass the tensor to embedding vector -. we gonna get th emebedding for that tensor\n\n\nto get emebedding for anything we need to pass it to the C\n\n'

In [25]:
embedding = C[X]
embedding

tensor([[[-0.4801, -0.5718],
         [-0.4801, -0.5718],
         [-0.4801, -0.5718]],

        [[-0.4801, -0.5718],
         [-0.4801, -0.5718],
         [ 0.4187,  1.1150]],

        [[-0.4801, -0.5718],
         [ 0.4187,  1.1150],
         [ 1.0437, -0.2197]],

        [[ 0.4187,  1.1150],
         [ 1.0437, -0.2197],
         [ 1.0437, -0.2197]],

        [[ 1.0437, -0.2197],
         [ 1.0437, -0.2197],
         [-0.3303,  0.4769]],

        [[-0.4801, -0.5718],
         [-0.4801, -0.5718],
         [-0.4801, -0.5718]],

        [[-0.4801, -0.5718],
         [-0.4801, -0.5718],
         [ 1.0341,  0.2543]],

        [[-0.4801, -0.5718],
         [ 1.0341,  0.2543],
         [ 0.5152, -0.1842]],

        [[ 1.0341,  0.2543],
         [ 0.5152, -0.1842],
         [-0.3285,  0.0651]],

        [[ 0.5152, -0.1842],
         [-0.3285,  0.0651],
         [ 1.3031,  1.1813]],

        [[-0.3285,  0.0651],
         [ 1.3031,  1.1813],
         [-0.3285,  0.0651]],

        [[ 1.3031,  1

In [26]:
embedding.shape

torch.Size([32, 3, 2])

now our input is embeeded

In [27]:
# so to convert the input vector to 2 dimensional space there are manu ways to represent it
# but one of the effective and easiest way pass dotview  .view(x,6)

embedding.view(-1, 6)

tensor([[-0.4801, -0.5718, -0.4801, -0.5718, -0.4801, -0.5718],
        [-0.4801, -0.5718, -0.4801, -0.5718,  0.4187,  1.1150],
        [-0.4801, -0.5718,  0.4187,  1.1150,  1.0437, -0.2197],
        [ 0.4187,  1.1150,  1.0437, -0.2197,  1.0437, -0.2197],
        [ 1.0437, -0.2197,  1.0437, -0.2197, -0.3303,  0.4769],
        [-0.4801, -0.5718, -0.4801, -0.5718, -0.4801, -0.5718],
        [-0.4801, -0.5718, -0.4801, -0.5718,  1.0341,  0.2543],
        [-0.4801, -0.5718,  1.0341,  0.2543,  0.5152, -0.1842],
        [ 1.0341,  0.2543,  0.5152, -0.1842, -0.3285,  0.0651],
        [ 0.5152, -0.1842, -0.3285,  0.0651,  1.3031,  1.1813],
        [-0.3285,  0.0651,  1.3031,  1.1813, -0.3285,  0.0651],
        [ 1.3031,  1.1813, -0.3285,  0.0651, -0.3303,  0.4769],
        [-0.4801, -0.5718, -0.4801, -0.5718, -0.4801, -0.5718],
        [-0.4801, -0.5718, -0.4801, -0.5718, -0.3303,  0.4769],
        [-0.4801, -0.5718, -0.3303,  0.4769,  1.3031,  1.1813],
        [-0.3303,  0.4769,  1.3031,  1.1

## Hidden Layer

In [28]:
## now if we want to pass it to the second layer

# consider second layer as weight w1 and bias b1
# then o/p of second layer = i/p @w1 + b1

#lets consider we have 100 weights in second layer such that we have 100 biases in second layer too h = tanh(w1*x1 + b1)

W1 = torch.rand((6,100))
B1 = torch.rand(100)

In [29]:
h = torch.tanh(embedding.view(-1, 6) @ W1 + B1)
h

tensor([[-0.6272, -0.8217, -0.9371,  ..., -0.7860, -0.8345, -0.0813],
        [ 0.5613,  0.0244,  0.6126,  ..., -0.6147,  0.4454,  0.5109],
        [ 0.4501,  0.6037,  0.6672,  ...,  0.6337,  0.7415,  0.9378],
        ...,
        [ 0.9994,  0.9849,  0.9585,  ..., -0.0398,  0.9972,  0.7091],
        [ 0.5349, -0.0637, -0.0439,  ...,  0.7753,  0.6206,  0.8619],
        [ 0.9818,  0.8723,  0.8892,  ...,  0.9315,  0.9734,  0.5931]])

In [30]:
h.shape

torch.Size([32, 100])

In [31]:
"""
-> We are creating the output layer here -> output layer = weight * hidden layer + Bias

-> but we have only 27 character, so the layer needs to be 27 weights + 27 weights i.e., we need to take 100 inputs and give only 27 o/p

->


"""

W2 = torch.randn((100,27))
B2 = torch.randn(27)

In [32]:
logits = h @ W2+ B2
logits

tensor([[  1.1739,  -4.6670,   7.8754,   7.1339,   0.7039,  -1.7191, -10.0511,
          -4.6246,   5.6103,  -2.3767,  -1.7321,  -0.7345,  10.3900,   1.0577,
           0.2727,   1.5749,   3.6362,  -0.3643,  -9.6544,  -3.3648,  -6.9878,
          -2.0819,  -2.3028,  -6.2240,  -1.0850,  -1.2537,  -3.2235],
        [  1.7919,  10.5477,  -6.6625,   3.7009,   0.0461,   4.8559,  -2.9863,
           8.6996,  -0.7946,   3.3162,   2.7923,   0.5470,  -1.8288,   3.8888,
           1.4029,   1.7446,   0.9335,  -7.2009,  -2.6945,  -4.7039,   0.9766,
           0.7695,  -4.7156,   3.6152,  -3.1825,  -4.9716,   0.5876],
        [  2.5625,  13.3951,  -6.5449,  -7.3383,   0.1051,   5.5425,   8.9715,
           9.4398,  -6.6858,   8.8093,   9.9245,   1.3003,  -9.5754,  -0.2307,
           1.1340,   4.4511,  -1.0242,  -1.5479,  10.0884,   5.7848,   4.3789,
           4.1966,   2.7485,   6.6056,  -1.8036,   1.2418,   2.9285],
        [ -1.0134,  12.6199,  -9.6470,  -8.6922,   3.4526,   4.9844,  12.1842,


In [33]:
counts = logits.exp()
counts

tensor([[3.2347e+00, 9.4002e-03, 2.6319e+03, 1.2537e+03, 2.0217e+00, 1.7923e-01,
         4.3137e-05, 9.8072e-03, 2.7324e+02, 9.2853e-02, 1.7691e-01, 4.7976e-01,
         3.2533e+04, 2.8797e+00, 1.3135e+00, 4.8301e+00, 3.7948e+01, 6.9470e-01,
         6.4144e-05, 3.4568e-02, 9.2309e-04, 1.2470e-01, 9.9979e-02, 1.9813e-03,
         3.3790e-01, 2.8544e-01, 3.9815e-02],
        [6.0009e+00, 3.8090e+04, 1.2779e-03, 4.0484e+01, 1.0472e+00, 1.2850e+02,
         5.0472e-02, 6.0006e+03, 4.5176e-01, 2.7555e+01, 1.6319e+01, 1.7280e+00,
         1.6060e-01, 4.8851e+01, 4.0669e+00, 5.7236e+00, 2.5435e+00, 7.4591e-04,
         6.7575e-02, 9.0601e-03, 2.6553e+00, 2.1587e+00, 8.9549e-03, 3.7158e+01,
         4.1483e-02, 6.9321e-03, 1.7997e+00],
        [1.2968e+01, 6.5679e+05, 1.4375e-03, 6.5017e-04, 1.1109e+00, 2.5533e+02,
         7.8752e+03, 1.2579e+04, 1.2485e-03, 6.6960e+03, 2.0424e+04, 3.6705e+00,
         6.9415e-05, 7.9402e-01, 3.1080e+00, 8.5722e+01, 3.5909e-01, 2.1269e-01,
         2.4063e+

In [34]:
probs  = counts/counts.sum(1, keepdims = True )
probs

tensor([[8.8026e-05, 2.5581e-07, 7.1621e-02, 3.4118e-02, 5.5016e-05, 4.8775e-06,
         1.1739e-09, 2.6688e-07, 7.4357e-03, 2.5268e-06, 4.8143e-06, 1.3056e-05,
         8.8533e-01, 7.8366e-05, 3.5744e-05, 1.3144e-04, 1.0327e-03, 1.8905e-05,
         1.7456e-09, 9.4071e-07, 2.5120e-08, 3.3934e-06, 2.7207e-06, 5.3918e-08,
         9.1954e-06, 7.7676e-06, 1.0835e-06],
        [1.3510e-04, 8.5753e-01, 2.8771e-08, 9.1144e-04, 2.3577e-05, 2.8930e-03,
         1.1363e-06, 1.3510e-01, 1.0171e-05, 6.2037e-04, 3.6741e-04, 3.8903e-05,
         3.6157e-06, 1.0998e-03, 9.1562e-05, 1.2886e-04, 5.7263e-05, 1.6793e-08,
         1.5214e-06, 2.0398e-07, 5.9781e-05, 4.8600e-05, 2.0161e-07, 8.3656e-04,
         9.3394e-07, 1.5607e-07, 4.0519e-05],
        [1.7764e-05, 8.9966e-01, 1.9690e-09, 8.9059e-10, 1.5217e-06, 3.4974e-04,
         1.0787e-02, 1.7230e-02, 1.7102e-09, 9.1721e-03, 2.7977e-02, 5.0278e-06,
         9.5084e-11, 1.0876e-06, 4.2573e-06, 1.1742e-04, 4.9188e-07, 2.9133e-07,
         3.2961e-

In [35]:
### Probs gives us the probability of what character comes next in the sequence, higher probability = high chance of coming next.
# so now i want to see what is the predicted probability for the right label i.e., we know true o/p from training data
# now we pluck out what model gave the probability for tru o/p
# that can be achieved by for o/p 1 its row 1 and column is going to be the true o/p form emma its e i.r., 5
# so in prob matrix to see what is the probability of predicting e is [1,5]
# for second o/p its [2,11]
# for third o/p its [3,5]

#inshortcut this can be written as [torch.arange(32),Y] because y has its all labels

In [36]:
probs[torch.arange(32), Y] # this is given the predicted probabilities for true label

tensor([4.8775e-06, 1.0998e-03, 1.0876e-06, 4.4988e-01, 1.1040e-06, 1.3144e-04,
        6.5186e-05, 3.7206e-03, 2.5078e-06, 1.9206e-03, 2.7475e-02, 4.2062e-07,
        2.5581e-07, 1.1452e-05, 9.6936e-01, 2.3341e-07, 2.5268e-06, 1.7533e-06,
        2.8250e-09, 3.9282e-04, 7.6607e-04, 2.9305e-10, 1.3433e-10, 4.7008e-01,
        2.7721e-06, 9.4071e-07, 1.3536e-04, 4.9803e-06, 1.4788e-04, 2.3806e-04,
        1.9308e-01, 1.0038e-05])

In [37]:
loss = -probs[torch.arange(32), Y].log().mean()
loss # this is the loss of correct prediction

tensor(10.4728)

In [41]:
## Summarizing everything nd writing together
X#input

tensor([[ 0,  0,  0],
        [ 0,  0,  5],
        [ 0,  5, 13],
        [ 5, 13, 13],
        [13, 13,  1],
        [ 0,  0,  0],
        [ 0,  0, 15],
        [ 0, 15, 12],
        [15, 12,  9],
        [12,  9, 22],
        [ 9, 22,  9],
        [22,  9,  1],
        [ 0,  0,  0],
        [ 0,  0,  1],
        [ 0,  1, 22],
        [ 1, 22,  1],
        [ 0,  0,  0],
        [ 0,  0,  9],
        [ 0,  9, 19],
        [ 9, 19,  1],
        [19,  1,  2],
        [ 1,  2,  5],
        [ 2,  5, 12],
        [ 5, 12, 12],
        [12, 12,  1],
        [ 0,  0,  0],
        [ 0,  0, 19],
        [ 0, 19, 15],
        [19, 15, 16],
        [15, 16,  8],
        [16,  8,  9],
        [ 8,  9,  1]])

In [44]:
Y #o/p

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9,  1,  0,  1, 22,  1,  0,  9, 19,
         1,  2,  5, 12, 12,  1,  0, 19, 15, 16,  8,  9,  1,  0])

In [97]:
g = torch.Generator().manual_seed(2147483647) # this is used for generating same weights from the tutorial
C = torch.rand((27,2), generator=g) #Embedding layer( we choosed 2 dimensional embedding for 27 charcters
W1 = torch.randn((6,100), generator=g)
B1 = torch.rand(100, generator = g)
W2 = torch.rand((100,27), generator = g)
B2 = torch.rand(27, generator = g)
parameters = [C, W1, B1, W2, B2]
sum(p.nelement() for p in parameters) # number of parameters in total

3481

In [72]:
embedding = C[X] #(32,3,2)
Hidden_Layer = torch.tanh(embedding.view(-1,6)@ W1 + B1) #(32, 100)
logits = Hidden_Layer @ W2 + B2 # (32,27)
counts = logits.exp()
probability = counts/counts.sum(1, keepdims = True)
loss = -probability[torch.arange(32),Y].log().mean()
loss

tensor(4.5415)

In [73]:
F.cross_entropy(logits,Y)# this step is same step we do for calculating the loss

tensor(4.5415)

In [74]:
""""
counts = logits.exp()
probability = counts/counts.sum(1, keepdims = True)
loss = -probability[torch.arange(32),Y].log().mean()

=

F.cross_entropy(logits,Y)# this step is same step we do for calculating the loss

# but F.cross_entrophy is very effective the above stepo we did is very ineffective but only to understading we did that

in future allway use F.cross_entrophy which is memory efficenta nd does all calculations correctly


make sure you allways use cross_entrophy ( because in many scenarios our manual calculation of loss fails)

Forward and  backward pass will be much efficient when we us ethe cross entrophy

"""

'"\ncounts = logits.exp()\nprobability = counts/counts.sum(1, keepdims = True)\nloss = -probability[torch.arange(32),Y].log().mean()\n\n=\n\nF.cross_entropy(logits,Y)# this step is same step we do for calculating the loss\n\n# but F.cross_entrophy is very effective the above stepo we did is very ineffective but only to understading we did that\n\nin future allway use F.cross_entrophy which is memory efficenta nd does all calculations correctly\n\n\nmake sure you allways use cross_entrophy ( because in many scenarios our manual calculation of loss fails)\n\nForward and  backward pass will be much efficient when we us ethe cross entrophy\n\n'

## Cleaner version of modeling

In [134]:
g = torch.Generator().manual_seed(2147483647) # this is used for generating same weights from the tutorial
C = torch.rand((27,2), generator=g) #Embedding layer( we choosed 2 dimensional embedding for 27 charcters
W1 = torch.randn((6,100), generator=g)
B1 = torch.rand(100, generator = g)
W2 = torch.rand((100,27), generator = g)
B2 = torch.rand(27, generator = g)
parameters = [C, W1, B1, W2, B2]
sum(p.nelement() for p in parameters) # number of parameters in total

3481

In [135]:
for p in parameters:
    p.requires_grad = True

In [76]:
# Forward pass
embedding = C[X] #(32,3,2)
Hidden_Layer = torch.tanh(embedding.view(-1,6)@ W1 + B1) #(32, 100)
logits = Hidden_Layer @ W2 + B2 # (32,27)
loss = F.cross_entropy(logits, Y)
print(loss.item())

# backward pass

for p in parameters:
    p.grad = None
loss.backward()
# update the weights
for p in parameters:
    p.data = p.data + (-0.1 * p.grad)


4.54152774810791


In [78]:
# so every time we run this the weights keeps on updating

for _ in range(1000):
    # Forward pass
    embedding = C[X] #(32,3,2)
    Hidden_Layer = torch.tanh(embedding.view(-1,6)@ W1 + B1) #(32, 100)
    logits = Hidden_Layer @ W2 + B2 # (32,27)
    loss = F.cross_entropy(logits, Y)
    print(loss.item())

    # backward pass

    for p in parameters:
        p.grad = None
    loss.backward()
    # update the weights
    for p in parameters:
        p.data = p.data + (-0.1 * p.grad)

1.3187161684036255
1.3123947381973267
1.306126356124878
1.2999099493026733
1.2937445640563965
1.2876286506652832
1.2815616130828857
1.2755415439605713
1.2695677280426025
1.2636388540267944
1.2577543258666992
1.2519116401672363
1.246111273765564
1.240350604057312
1.2346291542053223
1.2289457321166992
1.2232999801635742
1.217689037322998
1.2121131420135498
1.206571102142334
1.201061725616455
1.1955833435058594
1.1901358366012573
1.1847176551818848
1.1793279647827148
1.1739660501480103
1.168630838394165
1.1633211374282837
1.1580369472503662
1.1527764797210693
1.147539496421814
1.1423258781433105
1.1371334791183472
1.1319626569747925
1.1268126964569092
1.1216825246810913
1.1165722608566284
1.1114810705184937
1.1064084768295288
1.1013541221618652
1.0963175296783447
1.0912986993789673
1.0862971544265747
1.0813122987747192
1.076344609260559
1.0713934898376465
1.0664587020874023
1.0615407228469849
1.0566387176513672
1.0517534017562866
1.046884298324585
1.0420315265655518
1.0371956825256348
1.0

In [ ]:
## our neural n/w has low loss because it overfits because we only gave 32 i/p and 32 o/ps and trained dour model for that we 3k parameters for 32 examples the network will overfit single bath and getting low loss

'''
why loss is not becoming is zero for over fitting case with so many parameters ?

ans) in our training data for  i/p ... we have e, o, a, u, s as o/p, because all the starting character has ... in front of their names
due to sAME I/P HAS MULTIPLE O/P OVER MODEL HAS STILL LOSS IN CASE OF OVER FITTING T0O

    '''

# Creating Dataset for all words

In [137]:
## data set for neural network

block_size = 3 #Context_length: how many characters do we take to predict the next one?
X,Y =[],[] # X are the input to neural network and Y are  the labels of the neural network

for w in words:
    context = [0] * block_size

    for ch in w + '.':
        ix = stoi[ch]
        X.append(context)
        Y.append(ix)
        context = context[1:] + [ix]
X = torch.tensor(X)
Y = torch.tensor(Y)
X.shape, Y.shape

(torch.Size([228146, 3]), torch.Size([228146]))

In [138]:
g = torch.Generator().manual_seed(2147483647) # this is used for generating same weights from the tutorial
C = torch.randn((27,2), generator=g) #Embedding layer( we choosed 2 dimensional embedding for 27 charcters
W1 = torch.randn((6,100), generator=g)
B1 = torch.randn(100, generator = g)
W2 = torch.randn((100,27), generator = g)
B2 = torch.randn(27, generator = g)
parameters = [C, W1, B1, W2, B2]

In [139]:
sum(p.nelement() for p in parameters) # number of parameters in total

3481

In [140]:
for p in parameters:
    p.requires_grad = True

In [141]:
# so every time we run this the weights keeps on updating
for _ in range(1000):
    # Forward pass
    embedding = C[X] #(32,3,2)
    Hidden_Layer = torch.tanh(embedding.view(-1,6)@ W1 + B1) #(32, 100)
    logits = Hidden_Layer @ W2 + B2 # (32,27)
    loss = F.cross_entropy(logits, Y)
    print(loss.item())

    # backward pass

    for p in parameters:
        p.grad = None
    loss.backward()
    # update the weights
    for p in parameters:
        p.data = p.data + (-0.1 * p.grad)

19.505229949951172
17.084484100341797
15.776530265808105
14.833340644836426
14.002604484558105
13.253260612487793
12.57991886138916
11.983101844787598
11.47049331665039
11.051855087280273
10.709586143493652
10.407631874084473
10.127808570861816
9.864364624023438
9.614501953125
9.376439094543457
9.148943901062012
8.931109428405762
8.722230911254883
8.521748542785645
8.32922649383545
8.144325256347656
7.966790676116943
7.796449184417725
7.633184909820557
7.476906776428223
7.327520370483398
7.184884548187256
7.04879093170166
6.918951988220215
6.795017242431641
6.676602840423584
6.563317775726318
6.454788684844971
6.350668430328369
6.250642776489258
6.154431343078613
6.0617852210998535
5.972482204437256
5.886327743530273
5.803146839141846
5.722784042358398
5.64509391784668
5.569945335388184
5.497213363647461
5.4267802238464355
5.358535289764404
5.2923760414123535
5.228203296661377
5.165927886962891
5.10546875
5.046748161315918
4.98969841003418
4.934261798858643
4.880379676818848
4.82800579

In [102]:
## So training taking long time so in poytorch generally people will consider lot of mini batches and process them in to multiple small batche s

## to get mini batch we will do this
torch.randint(0, X.shape[0], (32,))

tensor([178201,  19598, 189969, 180573,  93173, 227570, 124706, 217284, 181533,
          9905, 178848,  36764,  91069,  61365, 217668,  18011,  81101,  99325,
        149333, 222166,  88646,  41626, 166278,  20113,  63472, 170630, 146087,
        150304,  82268,  10966,   9765, 214269])

In [116]:
for p in parameters:
    p.requires_grad = True

In [132]:
# so every time we run this the weights keeps on updating

for _ in range(100):

    ix = torch.randint(0, X.shape[0], (32,))
    # Forward pass
    embedding = C[X[ix]] #(32,3,2)
    Hidden_Layer = torch.tanh(embedding.view(-1,6)@ W1 + B1) #(32, 100)
    logits = Hidden_Layer @ W2 + B2 # (32,27)
    loss = F.cross_entropy(logits, Y[ix])
    print(loss.item())

    # backward pass

    for p in parameters:
        p.grad = None
    loss.backward()
    # update the weights
    for p in parameters:
        p.data = p.data + (-0.1 * p.grad)


63.102996826171875
72.2281494140625
77.70462799072266
53.06869888305664
71.79202270507812
63.936954498291016
76.86680603027344
50.71491622924805
52.626609802246094
57.2064323425293
63.42100524902344
63.934715270996094
55.886627197265625
61.298431396484375
59.826133728027344
67.75978088378906
51.124176025390625
74.03736114501953
58.24430847167969
44.324581146240234
72.9111328125
56.85130310058594
67.76238250732422
50.566490173339844
57.61076736450195
68.787353515625
60.94881057739258
50.06743240356445
41.504974365234375
50.62968444824219
43.43655014038086
56.62358474731445
49.547393798828125
49.7483024597168
38.577606201171875
53.53091812133789
52.3691520690918
60.785789489746094
50.25499725341797
52.74367141723633
44.358863830566406
43.72895812988281
53.458587646484375
57.12788772583008
48.348880767822266
58.23482894897461
36.028221130371094
37.15681076049805
51.946388244628906
40.8278694152832
39.22008514404297
41.145408630371094
42.253726959228516
44.29958724975586
47.7703742980957
5

In [133]:
#loss of entire model or loss of whole training data set
embedding = C[X] #(32,3,2)
Hidden_Layer = torch.tanh(embedding.view(-1,6)@ W1 + B1) #(32, 100)
logits = Hidden_Layer @ W2 + B2 # (32,27)
loss = F.cross_entropy(logits, Y)
loss

tensor(36.8598, grad_fn=<NllLossBackward0>)

In [147]:
## Finding the optimal Learning rate
learning_rates = 10**(torch.linspace(-3,0,1000))
learning_rates

tensor([0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0010, 0.0011,
        0.0011, 0.0011, 0.0011, 0.0011, 0.0011, 0.0011, 0.0011, 0.0011, 0.0011,
        0.0011, 0.0011, 0.0011, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012,
        0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0012, 0.0013, 0.0013, 0.0013,
        0.0013, 0.0013, 0.0013, 0.0013, 0.0013, 0.0013, 0.0013, 0.0013, 0.0014,
        0.0014, 0.0014, 0.0014, 0.0014, 0.0014, 0.0014, 0.0014, 0.0014, 0.0014,
        0.0015, 0.0015, 0.0015, 0.0015, 0.0015, 0.0015, 0.0015, 0.0015, 0.0015,
        0.0015, 0.0016, 0.0016, 0.0016, 0.0016, 0.0016, 0.0016, 0.0016, 0.0016,
        0.0016, 0.0017, 0.0017, 0.0017, 0.0017, 0.0017, 0.0017, 0.0017, 0.0017,
        0.0018, 0.0018, 0.0018, 0.0018, 0.0018, 0.0018, 0.0018, 0.0018, 0.0019,
        0.0019, 0.0019, 0.0019, 0.0019, 0.0019, 0.0019, 0.0019, 0.0020, 0.0020,
        0.0020, 0.0020, 0.0020, 0.0020, 0.0020, 0.0021, 0.0021, 0.0021, 0.0021,
        0.0021, 0.0021, 0.0021, 0.0022, 

In [148]:
# so every time we run this the weights keeps on updating
lri = []
lossi = []

for i in range(1000):
    #mini batch
    ix = torch.randint(0, X.shape[0], (32,))

    # Forward pass
    embedding = C[X[ix]] #(32,3,2)
    Hidden_Layer = torch.tanh(embedding.view(-1,6)@ W1 + B1) #(32, 100)
    logits = Hidden_Layer @ W2 + B2 # (32,27)
    loss = F.cross_entropy(logits, Y[ix])
    print(loss.item())

    # backward pass
    for p in parameters:
        p.grad = None
    loss.backward()

    # update the weights
    lr = learning_rates[i]
    for p in parameters:
        p.data = p.data + (-lr * p.grad)
    lri.append(lr)
    lossi.append(loss.item())


2.5044195652008057
2.605086088180542
2.5266778469085693
2.8355984687805176
2.394714593887329
2.6737442016601562
2.5800387859344482
2.655266046524048
2.640887498855591
2.7048661708831787
2.5208592414855957
2.7826919555664062
2.189084529876709
2.724280834197998
3.0088329315185547
2.461857318878174
2.6590371131896973
2.6130051612854004
2.556684970855713
2.6731133460998535
2.498938798904419
2.184372901916504
2.391960859298706
2.2629942893981934
2.490084171295166
2.6231496334075928
2.448230743408203
2.8153786659240723
2.6792073249816895
2.2862510681152344
2.2232565879821777
2.7774198055267334
2.4445290565490723
2.3220794200897217
2.687422037124634
2.614575147628784
2.136293411254883
3.021648406982422
2.7669873237609863
2.6312499046325684
2.4933176040649414
2.169806480407715
2.3141815662384033
2.464982509613037
3.055375337600708
2.4708337783813477
2.4383184909820557
2.6338961124420166
2.767061710357666
2.9400711059570312
2.561983108520508
2.332606077194214
2.4984805583953857
2.63000607490539

In [150]:
plt.plot(lri, lossi)

In [151]:
lri

[tensor(0.0010),
 tensor(0.0010),
 tensor(0.0010),
 tensor(0.0010),
 tensor(0.0010),
 tensor(0.0010),
 tensor(0.0010),
 tensor(0.0010),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0011),
 tensor(0.0012),
 tensor(0.0012),
 tensor(0.0012),
 tensor(0.0012),
 tensor(0.0012),
 tensor(0.0012),
 tensor(0.0012),
 tensor(0.0012),
 tensor(0.0012),
 tensor(0.0012),
 tensor(0.0012),
 tensor(0.0012),
 tensor(0.0013),
 tensor(0.0013),
 tensor(0.0013),
 tensor(0.0013),
 tensor(0.0013),
 tensor(0.0013),
 tensor(0.0013),
 tensor(0.0013),
 tensor(0.0013),
 tensor(0.0013),
 tensor(0.0013),
 tensor(0.0014),
 tensor(0.0014),
 tensor(0.0014),
 tensor(0.0014),
 tensor(0.0014),
 tensor(0.0014),
 tensor(0.0014),
 tensor(0.0014),
 tensor(0.0014),
 tensor(0.0014),
 tensor(0.0015),
 tensor(0.0015),
 tensor(0.0015),
 tensor(0.0015),
 tensor(0.0015