# Alternative Approach of Bi-gram model into Neural Network

### Our Neural network model is still going to be Bi-gram character level model

In [4]:
## Creating the training set of the Bi-gram
import pandas as pd
import numpy as np
import torch
import matplotlib.pyplot as plt
#%matplotlib inline

words = open('names.txt').read().splitlines()
chars = (sorted(list(set(''.join(words)))))# Now we are taking all the names join them as massive string and throws out all the duplicates using set function and get the list of strings used

stoi = { s:i+1 for i,s in enumerate(chars)}# String to integer(stoi) is a dictionary, where we are converting above used string characters  to integer.
stoi['.'] = 0 #Now we want to add '.' to this as well to our character to integer dictionary.
itos = { i:s for s,i in stoi.items()}## Now Similarly we need to create the integer to string converter

In [31]:
# Create the training set of bigrams(x,y)

xs, ys = [], []

for w in words[:1]:
    chs = ['.'] + list(w) + ['.'] #we are taking the character string, because we want to see how the distribution is
    for ch1, ch2 in zip(chs, chs[1:]):
        ix1 = stoi[ch1]
        ix2 = stoi[ch2]
        xs.append(ix1)
        ys.append(ix2)
        print(ch1, ch2)

#we are constructing xs and ys a tensor
xs = torch.tensor(xs)
ys = torch.tensor(ys)

. e
e m
m m
m a
a .


In [32]:
xs

tensor([ 0,  5, 13, 13,  1])

In [33]:
ys

tensor([ 5, 13, 13,  1,  0])

In [34]:
""" so what we the xs and ys tell you is
1)as we are using bi-gram when one character is input, we need to get the another charter as o/p
2)when xs[0] is input we have to have high probability to get the o/p ys[0] as next character i.e., when the input is 0 we need to get 5 as the next character with high probability i.e.,
3) in other terms when (.) is input to model we need to provide high probability to get the character (e) next because in .emma. the first 2 character are . and e

4) similarly when we need to have high probabilities
  a) for this example .emma. -> (.) as input (e) must has high probability o/p     ie.,  -> (0) as i/p -> high probability o/p must be ->(5)
                             -> (e) as input (m) must has high probability o/p     ie.,  -> (5) as i/p -> high probability o/p must be ->(13)
                             -> (m) as input (m) must has high probability o/p     ie.,  -> (13) as i/p -> high probability o/p must be ->(13)
                             -> (m) as input (a) must has high probability o/p     ie.,  -> (13) as i/p -> high probability o/p must be ->(1)
                             -> (a) as input (.) must has high probability o/p     ie.,  -> (1) as i/p -> high probability o/p must be ->(0)
"""

' so what we the xs and ys tell you is\n1)as we are using bi-gram when one character is input, we need to get the another charter as o/p\n2)when xs[0] is input we have to have high probability to get the o/p ys[0] as next character i.e., when the input is 0 we need to get 5 as the next character with high probability i.e.,\n3) in other terms when (.) is input to model we need to provide high probability to get the character (e) next because in .emma. the first 2 character are . and e\n\n4) similarly when we need to have high probabilities\n  a) for this example .emma. -> (.) as input (e) must has high probability o/p     ie.,  -> (0) as i/p -> high probabily o/p must be ->(5)\n                             -> (e) as input (m) must has high probability o/p     ie.,  -> (5) as i/p -> high probabily o/p must be ->(13)\n                             -> (m) as input (m) must has high probability o/p     ie.,  -> (13) as i/p -> high probabily o/p must be ->(13)\n                             ->

In [36]:
## now we need to assume how we need to train this numbers to neural networks

## we need to use one hot encoding to encode this number vector

import torch.nn.functional as F
xs_encoded = F.one_hot(xs, num_classes=27)
xs_encoded

tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0]])

In [52]:
# the neural networks like to have the flot number as input so the encoded values must in the float time
xs_encoded = xs_encoded.float()
xs_encoded

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Randomly initialization of weights

In [49]:
W = torch.randn((27,27))
W

tensor([[-1.0086e+00,  5.8980e-02, -1.7584e+00, -2.7064e-01, -1.9299e-01,
          1.0229e+00, -9.2017e-01,  8.9978e-01, -4.0465e-01,  1.4029e-01,
          2.4143e-02,  2.0946e+00, -5.3770e-01,  4.0817e-01,  8.5065e-01,
          3.0688e-01, -5.8246e-01, -6.2027e-01,  1.4835e+00, -7.5611e-01,
         -6.9630e-01, -4.3281e-01,  1.3918e+00, -1.2550e-01, -9.8927e-01,
          8.7319e-01, -2.6244e-01],
        [ 8.8267e-01,  6.3231e-01,  6.8623e-01, -4.6905e-01, -4.4160e-01,
          4.0951e-01, -9.6335e-01,  1.2914e+00,  2.8186e-01,  2.9014e-01,
         -2.4149e-01, -1.0776e+00, -1.2465e+00,  8.2353e-01,  1.6169e-01,
         -3.3944e-01, -5.4989e-01,  7.5682e-01, -3.1158e-01,  1.1534e+00,
         -2.8485e-01, -7.4605e-01,  3.8226e-01, -5.1608e-01,  1.0015e+00,
          1.4688e+00,  4.3623e-01],
        [ 1.4937e+00, -8.8609e-01, -5.9392e-03, -1.4784e+00,  1.0096e+00,
          2.1784e-01,  1.6418e+00,  5.8012e-01, -4.0046e-01,  4.3673e-02,
          3.5640e-01,  1.6198e+00, -4.04

In [50]:
xs_encoded @ W #@ is is matrix multiplication operator in torch

tensor([[-1.0086,  0.0590, -1.7584, -0.2706, -0.1930,  1.0229, -0.9202,  0.8998,
         -0.4046,  0.1403,  0.0241,  2.0946, -0.5377,  0.4082,  0.8506,  0.3069,
         -0.5825, -0.6203,  1.4835, -0.7561, -0.6963, -0.4328,  1.3918, -0.1255,
         -0.9893,  0.8732, -0.2624],
        [ 0.2128, -0.3675,  0.4276,  0.6860,  2.7290, -1.3649, -1.4858,  1.1199,
         -0.7253, -0.7939, -0.4171,  0.2485, -2.0380, -2.0876, -0.6004,  0.7073,
          0.4543, -0.5520,  2.1249, -1.2828, -0.9456,  0.4243,  1.5663,  1.1979,
          0.5975,  0.5849, -0.2889],
        [-2.0329,  0.1404,  2.8447, -0.3599,  1.2112,  0.8587,  0.3014, -1.7417,
          0.4578, -1.3648,  0.4212, -0.9624,  0.3698, -1.0630, -1.3633,  2.3991,
         -1.5942, -0.7501, -0.6390,  1.2018, -1.0455, -0.3285,  0.3863, -0.0350,
          0.2051, -0.3074,  1.0788],
        [-2.0329,  0.1404,  2.8447, -0.3599,  1.2112,  0.8587,  0.3014, -1.7417,
          0.4578, -1.3648,  0.4212, -0.9624,  0.3698, -1.0630, -1.3633,  2.3991

In [ ]:
# we are doing matrixs multiplication to get the o/p of the 1st layer

In [55]:
## xs_encode = [5*27] matrix
## W =[27 * 1 ] Matrix
## Xs Encode * W = [5*27] * [27*27] = [5*27]
(xs_encoded @ W) [1,1]

tensor(-0.3675)

In [ ]:
"""
I will run though an example to explain how matrix multiplication is done

1. we consider the row one of matix xs_encoded and multiple it with the column one of matrix W this is nothing but the dot product of an element
2. we can do it by writing down the function xs_encoded @ w similfies this process much fatser
regular example beloe
"""

In [56]:
(xs_encoded[1] * W[:,1]).sum()

tensor(-0.3675)

In [ ]:
#you can notice we got the same result
"""
1. we want to provide probability distribution for each of the 27 characters
2. but we have to come out with precise semantics for exactly how we can interpret this numbers.
3. probabilities has only positive numbers and counts are also integers and positive, counts are not really good to o/p from neural network
4.so what neural net going to o/p? How are we going to interpret the number? the Neural network give us log count instead of 27 numbers not like tensor matrix with counts in it.
5. instead what NN gives is log count then we take exponential  we get the values between [0 and infinity]


see below for exponenetial


"""

In [59]:
(xs_encoded @ W).exp()

tensor([[ 0.3647,  1.0608,  0.1723,  0.7629,  0.8245,  2.7814,  0.3984,  2.4591,
          0.6672,  1.1506,  1.0244,  8.1221,  0.5841,  1.5041,  2.3412,  1.3592,
          0.5585,  0.5378,  4.4084,  0.4695,  0.4984,  0.6487,  4.0219,  0.8821,
          0.3718,  2.3945,  0.7692],
        [ 1.2372,  0.6925,  1.5335,  1.9857, 15.3177,  0.2554,  0.2263,  3.0646,
          0.4842,  0.4521,  0.6590,  1.2821,  0.1303,  0.1240,  0.5486,  2.0285,
          1.5751,  0.5758,  8.3725,  0.2773,  0.3884,  1.5285,  4.7890,  3.3130,
          1.8176,  1.7948,  0.7491],
        [ 0.1310,  1.1507, 17.1971,  0.6978,  3.3574,  2.3600,  1.3517,  0.1752,
          1.5807,  0.2554,  1.5238,  0.3820,  1.4474,  0.3454,  0.2558, 11.0133,
          0.2031,  0.4723,  0.5278,  3.3260,  0.3515,  0.7200,  1.4716,  0.9656,
          1.2276,  0.7354,  2.9412],
        [ 0.1310,  1.1507, 17.1971,  0.6978,  3.3574,  2.3600,  1.3517,  0.1752,
          1.5807,  0.2554,  1.5238,  0.3820,  1.4474,  0.3454,  0.2558, 11.0133

In [ ]:
## we can notice all the values are +ve and this are counts

In [60]:
logits = xs_encoded @ W #which are technically called log counts
counts = logits.exp() #Equivalent to N Matrix with counts we made earlier
# now we want to normalise the values by row/layer

probs = counts/counts.sum(1, keepdims = True)
probs

tensor([[0.0089, 0.0258, 0.0042, 0.0185, 0.0200, 0.0676, 0.0097, 0.0598, 0.0162,
         0.0280, 0.0249, 0.1974, 0.0142, 0.0366, 0.0569, 0.0330, 0.0136, 0.0131,
         0.1072, 0.0114, 0.0121, 0.0158, 0.0978, 0.0214, 0.0090, 0.0582, 0.0187],
        [0.0224, 0.0125, 0.0278, 0.0360, 0.2775, 0.0046, 0.0041, 0.0555, 0.0088,
         0.0082, 0.0119, 0.0232, 0.0024, 0.0022, 0.0099, 0.0367, 0.0285, 0.0104,
         0.1517, 0.0050, 0.0070, 0.0277, 0.0868, 0.0600, 0.0329, 0.0325, 0.0136],
        [0.0023, 0.0205, 0.3062, 0.0124, 0.0598, 0.0420, 0.0241, 0.0031, 0.0281,
         0.0045, 0.0271, 0.0068, 0.0258, 0.0061, 0.0046, 0.1961, 0.0036, 0.0084,
         0.0094, 0.0592, 0.0063, 0.0128, 0.0262, 0.0172, 0.0219, 0.0131, 0.0524],
        [0.0023, 0.0205, 0.3062, 0.0124, 0.0598, 0.0420, 0.0241, 0.0031, 0.0281,
         0.0045, 0.0271, 0.0068, 0.0258, 0.0061, 0.0046, 0.1961, 0.0036, 0.0084,
         0.0094, 0.0592, 0.0063, 0.0128, 0.0262, 0.0172, 0.0219, 0.0131, 0.0524],
        [0.0607, 0.0472,

In [61]:
probs[0]

tensor([0.0089, 0.0258, 0.0042, 0.0185, 0.0200, 0.0676, 0.0097, 0.0598, 0.0162,
        0.0280, 0.0249, 0.1974, 0.0142, 0.0366, 0.0569, 0.0330, 0.0136, 0.0131,
        0.1072, 0.0114, 0.0121, 0.0158, 0.0978, 0.0214, 0.0090, 0.0582, 0.0187])

In [62]:
probs[0].sum() # it will be always one

tensor(1.)

In [ ]:
## explanation
"""
1) input_char = .emma ->stoi function to get [0, 5, 13, 13, 1]

a) Xs = [0, 5, 13, 13, 1] #which is input
b) Xs_encoded = tensor with onehot encoding 5 numbers in input  * 27 characters  so encoded tensor matrix is [5*27]
c) we feed only the first character as input to the neural network
d) it has the hidden layer which does softmax function ( i.e., Ek/sum ek )
e) we didn't directly use softmax we calculated it like this... log counts = encoded vector* weights
f) we got the log count we did inverse function to counts then we did layer normalization.. above 2 steps ar enothing but softmax function
g)and we got the o/p as probs...

2) breakdown of probs.. probs [0] means when . is passed as input to the model what is the most likely of the next outcome out of 27 characters.....  we got the highest probabilty at 0.0676 which is the index 6 position which is e
pron[1] gives as when e is passed what is the most likely out outome of all 27 charcters... and so on,,,,

3) i will write whole blockl of code clearly in below step.

4) if we tune weights W the probabilities coming out will definitely  gonna  change

"""

In [63]:
## neatly written organised together

xs

tensor([ 0,  5, 13, 13,  1])

In [64]:
ys

tensor([ 5, 13, 13,  1,  0])

In [65]:
## Randomly initialize 27 neuron weights . each neuron recieve 27 inputs

g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27,27), generator=g)

## Forward pass of neural networks

In [73]:
xs_encoded = F.one_hot(xs, num_classes=27).float()
logits = xs_encoded @ W # gives the log-counts
counts = logits.exp() # inverse of log = log then we get the counts
probs = counts/counts.sum(1, keepdims = True) # probabilities for next charcter

In [72]:
 ## now we want to calculate the loss

nlls = torch.zeros(5)
for i in range(5):
    x= xs[i].item()
    y = ys[i].item()
    print('--------')
    print('--------')
    print(f'bigram example {i+1}: {itos[x]}{itos[y]} (indexes {x},{y})')
    print('input to the neural net:', x)
    print('output probabilities from the neural net:', probs[i])
    print('label (actual next character):', y)
    p = probs[i, y]
    print('probability assigned by the net to the the correct character:', p.item())
    logp = torch.log(p)
    print('log likelihood:', logp.item())
    nll = -logp
    print('negative log likelihood:', nll.item())
    nlls[i] = nll

print('=========')
print('average negative log likelihood, i.e. loss =', nlls.mean().item())


--------
--------
bigram example 1: .e (indexes 0,5)
input to the neural net: 0
output probabilities from the neural net: tensor([0.0607, 0.0100, 0.0123, 0.0042, 0.0168, 0.0123, 0.0027, 0.0232, 0.0137,
        0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2378, 0.0603, 0.0025,
        0.0249, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1537, 0.1459])
label (actual next character): 5
probability assigned by the net to the the correct character: 0.01228625513613224
log likelihood: -4.399273872375488
negative log likelihood: 4.399273872375488
--------
--------
bigram example 2: em (indexes 5,13)
input to the neural net: 5
output probabilities from the neural net: tensor([0.0290, 0.0796, 0.0248, 0.0521, 0.1989, 0.0289, 0.0094, 0.0335, 0.0097,
        0.0301, 0.0702, 0.0228, 0.0115, 0.0181, 0.0108, 0.0315, 0.0291, 0.0045,
        0.0916, 0.0215, 0.0486, 0.0300, 0.0501, 0.0027, 0.0118, 0.0022, 0.0472])
label (actual next character): 13
probability assigned by the net to the the cor

In [ ]:
""""
# g = torch.Generator().manual_seed(2147483647)
# W = torch.randn((27,27), generator=g)
if keep on changing the weights the loss is going to change

but we cannot keep on changing the w value to find the optimal weights there fore we need to do back propogation  weights in proper way

with average negative likely hood

"""

In [74]:
probs

tensor([[0.0607, 0.0100, 0.0123, 0.0042, 0.0168, 0.0123, 0.0027, 0.0232, 0.0137,
         0.0313, 0.0079, 0.0278, 0.0091, 0.0082, 0.0500, 0.2378, 0.0603, 0.0025,
         0.0249, 0.0055, 0.0339, 0.0109, 0.0029, 0.0198, 0.0118, 0.1537, 0.1459],
        [0.0290, 0.0796, 0.0248, 0.0521, 0.1989, 0.0289, 0.0094, 0.0335, 0.0097,
         0.0301, 0.0702, 0.0228, 0.0115, 0.0181, 0.0108, 0.0315, 0.0291, 0.0045,
         0.0916, 0.0215, 0.0486, 0.0300, 0.0501, 0.0027, 0.0118, 0.0022, 0.0472],
        [0.0312, 0.0737, 0.0484, 0.0333, 0.0674, 0.0200, 0.0263, 0.0249, 0.1226,
         0.0164, 0.0075, 0.0789, 0.0131, 0.0267, 0.0147, 0.0112, 0.0585, 0.0121,
         0.0650, 0.0058, 0.0208, 0.0078, 0.0133, 0.0203, 0.1204, 0.0469, 0.0126],
        [0.0312, 0.0737, 0.0484, 0.0333, 0.0674, 0.0200, 0.0263, 0.0249, 0.1226,
         0.0164, 0.0075, 0.0789, 0.0131, 0.0267, 0.0147, 0.0112, 0.0585, 0.0121,
         0.0650, 0.0058, 0.0208, 0.0078, 0.0133, 0.0203, 0.1204, 0.0469, 0.0126],
        [0.0150, 0.0086,

In [ ]:
"""
 (.) as input (e) must has high probability o/p     ie.,  -> (0) as i/p -> high probability o/p must be ->(5)
                             -> (e) as input (m) must has high probability o/p     ie.,  -> (5) as i/p -> high probability o/p must be ->(13)
                             -> (m) as input (m) must has high probability o/p     ie.,  -> (13) as i/p -> high probability o/p must be ->(13)
                             -> (m) as input (a) must has high probability o/p     ie.,  -> (13) as i/p -> high probability o/p must be ->(1)
                             -> (a) as input (.) must has high probability o/p     ie.,  -> (1) as i/p -> high probability o/p must be ->(0)


                             so desired o/p variables are 5, 13,13,1,0
for the input vectors

lets see what our model has predicted the for our input vector
"""

In [76]:
probs[0,5],probs[1,13], probs[2,13], probs[3,13], probs [4,0]

(tensor(0.0123),
 tensor(0.0181),
 tensor(0.0267),
 tensor(0.0267),
 tensor(0.0150))

In [78]:
# we can see none of the prediction probability is hih , and we are in classification model

# like we are Classifying which one among the 5 output it closely match with

probs[torch.arange(5), ys]

tensor([0.0123, 0.0181, 0.0267, 0.0737, 0.0150])

In [79]:
## Negative log likely hood estimation can be achieved by
loss = -probs[torch.arange(5), ys].log().mean()
loss


tensor(3.7693)

In [80]:
#------- clean optimization step-------------------------------------

#input
xs

tensor([ 0,  5, 13, 13,  1])

In [81]:
#output
ys

tensor([ 5, 13, 13,  1,  0])

In [100]:
# random weights
g = torch.Generator().manual_seed(2147483647)
Wg = torch.randn((27,27), generator=g, requires_grad = True)

In [120]:
#Forward pass of NN
xs_encoded = F.one_hot(xs,num_classes=27).float()
logits = xs_encoded @ Wg
counts = logits.exp()
probs = counts/counts.sum(1, keepdims = True)
loss = -probs[torch.arange(5), ys].log().mean()  ## Negative log likely hood estimation can be achieved by
loss

tensor(3.6693, grad_fn=<NegBackward0>)

In [121]:
#Backward pass
Wg.grad = None # set to zero the gradient
loss.backward()

In [122]:
Wg.data += -0.1 * Wg.grad # this cell update the weights evertime

In [123]:
## putting loop and we can change the  loss function so the random weights keeps on updating

# --------- !!! OPTIMIZATION !!! yay, but this time actually --------------

# create the dataset
xs, ys = [], []
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    xs.append(ix1)
    ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples: ', num)

# initialize the 'network'
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27, 27), generator=g, requires_grad=True)

number of examples:  228146


In [133]:
# gradient descent
for k in range(500):

  # forward pass
  xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
  logits = xenc @ W # predict log-counts
  counts = logits.exp() # counts, equivalent to N
  probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
  loss = -probs[torch.arange(num), ys].log().mean() # negative log likely   hood
  print(loss.item())

  # backward pass
  W.grad = None # set to zero the gradient
  loss.backward()

  # update
  W.data += -50 * W.grad

2.480414390563965
2.480414390563965
2.480414390563965
2.4804141521453857
2.480414390563965
2.4804141521453857
2.480414390563965
2.4804141521453857
2.4804141521453857
2.4804141521453857
2.4804139137268066
2.4804136753082275
2.4804139137268066
2.4804136753082275
2.4804139137268066
2.4804136753082275
2.4804136753082275
2.4804134368896484
2.4804134368896484
2.4804136753082275
2.4804136753082275
2.4804136753082275
2.4804131984710693
2.4804131984710693
2.4804134368896484
2.4804131984710693
2.4804129600524902
2.4804131984710693
2.4804131984710693
2.4804129600524902
2.4804131984710693
2.4804131984710693
2.4804131984710693
2.4804129600524902
2.4804129600524902
2.480412721633911
2.480412483215332
2.480412483215332
2.480412721633911
2.480412483215332
2.480412483215332
2.480412721633911
2.480412483215332
2.480412483215332
2.480412483215332
2.480412721633911
2.480412483215332
2.480412244796753
2.480412483215332
2.480412483215332
2.480412244796753
2.480412006378174
2.480412006378174
2.48041200637817

In [134]:
logits = xenc @ W

"""
logits = xenc @ W
Meaning of steps we are assumming that this is one hot encoding multiplied weights which is nothing but the forward feed neural network

what happens here is

a). if we consider one hot vector has only 1 at 5 th position(e character will have) i.e., [0,0,0,0,1,0,0] multiplied to weights matrix which is column matrix with [w1, w2, w3, w4,w5, w6,w7]
the result will be [0,0,0,0,w5,0,0] so all the other weights literally became zero  logits will becomes only the 5th row of the weights


b)itis also something happend at the matrix we generated before which gives us the matrix visulaization  and returning the count, so we can say the countmtrix and exp(logits) is something similar


c) then we are normalizing and extracting the loss by -ve log likelyhood literally same as above


d) so the array/Tensor W(weights) after the optimization = count matrix we generated at starting


e) but for the count vector/matrix we added N+1 to smooth out the count matrix to ignore zero values-, what happens if we increase N+1 with N+100 > this smooth out the Prediction and make uniform distribution

f) so in our case if we make weights to zero, i.e., w = 0

    logits = xenc @ W # predict log-counts => logits = 0
    counts = logits.exp() # counts, equivalent to N => counts = 1( because e^0 =1)
    probs = counts / counts.sum(1, keepdims=True) # prob = 1

    *** so if we initialize the weights to zero we are getting the probability nearly uniform, this process is nothing but the label smoothing also called as regularixzation

    we can take entries of all weights and square them and take mean  and add to loss which acts as regularization with learning rate
"""

'\nMeaning of steps we are assumming that this is one hot encoding multiplied weights which is nothing but the forward feed neural network\n\nwhat happens here is \n'

### Regularization with learning rate

In [135]:
# gradient descent
for k in range(500):

  # forward pass
  xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
  logits = xenc @ W # predict log-counts
  counts = logits.exp() # counts, equivalent to N
  probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
  loss = -probs[torch.arange(num), ys].log().mean() + 0.01*(W**2).mean() #(0.01*(W**2).mean()) this is regularization with small learning rate   hood
  print(loss.item())

  # backward pass
  W.grad = None # set to zero the gradient
  loss.backward()

  # update
  W.data += -50 * W.grad

2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804024696350098
2.4804024696350098
2.4804024696350098
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804024696350098
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312164307
2.4804022312

In [ ]:
"""

if we increase ( N+ 100)  it will make the prediction more smooth and more uniform distrubution similarly  its nothing but increaseing the Learning_rate of this Regularization (0.01* (W**2).mean())

because as weights grow more the loss keep on increasing  then we are unable to

"""

In [143]:
g = torch.Generator().manual_seed(2147483647)

for i in range(50):

    out = []
    ix = 0

    while True:
        xenc = F.one_hot(torch.tensor([ix]), num_classes=27).float() # input to the network: one-hot encoding
        logits = xenc @ W # predict log-counts
        counts = logits.exp() # counts, equivalent to N
        probs = counts / counts.sum(1, keepdims=True)

        ix = torch.multinomial(probs, num_samples= 1, replacement = True, generator = g).item()
        out.append(itos[ix])

        if ix == 0:
            break
    print(''.join(out))


cexze.
momasurailezityha.
konimittain.
llayn.
ka.
da.
staiyaubrtthrigotai.
moliellavo.
ke.
teda.
ka.
emimmsade.
enkaviyny.
ftlspehinivenvtahlasu.
dsor.
br.
jol.
pen.
aisan.
ja.
feniee.
zem.
deru.
firit.
gaikajahahbevare.
kiysthelenaririenah.
keen.
x.
al.
kalmahavazeeromysos.
laitenimieegariseriyen.
k.
illeleldole.
meenisammigama.
mmin.
asharficalcalh.
ciayn.
asaza.
elanely.
chay.
rana.
ai.
yviamisashougen.
l.
beyncaro.
allan.
annutetoradrilia.
rddemkaha.
cahfahevara.
jala.


In [ ]:
## So this is the same model but we approached it differently with Neural network the o/p will really look same because of the input data


"""
Topics Covered

1. we introduce bi gram language model.
2. we learned how we can train our model and how we can sample our model.
3. how we can evaluate the quality of the model using -ve loge likely hood loss
4. we trained our model in two completely different ways that actually give the same results from ame model.
5. in first way we counted all the frequency/ counts of bi grams, in second way we used negative log likely hood loss as guide to optimize the frequency/counts to optimize the counts matrix so that loss is minimized in gradient based frame form
6. We noticed both of them gave the same result
7. gradient based framework is simiple, we use only single layer of neurons i.e., Xenc * Weights to calculate the logits , In future we goona increase the neural network layer , but the normalising and gradient based frame work remains same.
8. so we complexify the neural networks all the way to transformers

"""